# Generated by Django 4.2.2 on 2023-06-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("cover_image", models.ImageField(upload_to="book_covers/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rating", models.FloatField(default=0)),
                ("genre", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
            ],
        ),
    ]
